export const registries = {
  students: {
    label: "Students",
    singular: "Student",
    base: process.env.REACT_APP_STUDENT_API_URL || "http://localhost:5001",
    idField: "roll",
    idLabel: "Roll number",
    detailField: "address",
    detailLabel: "Address",
    namePlaceholder: "e.g. Avery Morgan",
    idPlaceholder: "e.g. ST-001",
    detailPlaceholder: "e.g. 24 Maple Avenue",
    icon: "students",
    color: "lavender",
    caption: "Curious minds, bright futures",
    description: "A little organization for every little learner.",
    formDescription: "Welcome a new learner to your school community.",
  },
  teachers: {
    label: "Teachers",
    singular: "Teacher",
    base: process.env.REACT_APP_TEACHER_API_URL || "http://localhost:5002",
    idField: "id",
    idLabel: "Teacher ID",
    detailField: "subject",
    detailLabel: "Subject",
    namePlaceholder: "e.g. Jamie Parker",
    idPlaceholder: "e.g. TC-001",
    detailPlaceholder: "e.g. Early learning",
    icon: "teachers",
    color: "peach",
    caption: "Guiding the next generation",
    description: "The inspiring people behind every new discovery.",
    formDescription: "Make room for another inspiring educator.",
  },
  employees: {
    label: "Employees",
    singular: "Employee",
    base: process.env.REACT_APP_EMPLOYEE_API_URL || "http://localhost:5003",
    idField: "id",
    idLabel: "Employee ID",
    detailField: "position",
    detailLabel: "Position",
    namePlaceholder: "e.g. Riley Bennett",
    idPlaceholder: "e.g. EM-001",
    detailPlaceholder: "e.g. Office administrator",
    icon: "employees",
    color: "mint",
    caption: "Keeping your school thriving",
    description: "Meet the team that makes every school day possible.",
    formDescription: "Bring a new team member into the fold.",
  },
};
